// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBEe9cpvh4XUwwjUk-qVmM8NxOU16oeqcY',
    appId: '1:729115762178:web:1213d19dfb82624974511b',
    messagingSenderId: '729115762178',
    projectId: 'chat-app-fef58',
    authDomain: 'chat-app-fef58.firebaseapp.com',
    storageBucket: 'chat-app-fef58.appspot.com',
    measurementId: 'G-JKL066TRE5',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAB3LREaqK7GVjbQVUAW-YWZ_CwuobVCcs',
    appId: '1:729115762178:android:b31abb558510527074511b',
    messagingSenderId: '729115762178',
    projectId: 'chat-app-fef58',
    storageBucket: 'chat-app-fef58.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtnPDqghQ09PCVRf3mXdCPRavGh9pS7Wg',
    appId: '1:729115762178:ios:21999b6f004d1e6b74511b',
    messagingSenderId: '729115762178',
    projectId: 'chat-app-fef58',
    storageBucket: 'chat-app-fef58.appspot.com',
    iosClientId: '729115762178-cbffqvrg95b1ov78ggsa25vnn2pjjshd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAtnPDqghQ09PCVRf3mXdCPRavGh9pS7Wg',
    appId: '1:729115762178:ios:21999b6f004d1e6b74511b',
    messagingSenderId: '729115762178',
    projectId: 'chat-app-fef58',
    storageBucket: 'chat-app-fef58.appspot.com',
    iosClientId: '729115762178-cbffqvrg95b1ov78ggsa25vnn2pjjshd.apps.googleusercontent.com',
    iosBundleId: 'com.example.chatApp',
  );
}
